---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Check for oh-my-zsh
      ansible.builtin.stat:
        path: /Users/{{ ansible_user_id }}/.oh-my-zsh
      register: stat_oh_my_zsh_result

    - name: Install oh-my-zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not stat_oh_my_zsh_result.stat.exists

    - name: Ensuring Homebrew is present
      ansible.builtin.stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail if no Homebrew detected
      ansible.builtin.fail:
        msg: Installing from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

    - name: Updating Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      when: homebrew_check.stat.exists
      changed_when: false

    - name: Add Homebrew taps
      community.general.homebrew_tap:
        name: "{{ homebrew_taps }}"
        state: present

    - name: Installing Homebrew Packages
      community.general.homebrew:
        name: "{{ homebrew_packages }}"
        state: present

    - name: Installing Homebrew Cask Packages
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_packages }}"
        state: present

    - name: Make sure Tor service is stopped
      ansible.builtin.command: brew services stop tor
      register: tor
      changed_when: false
      failed_when: "'Error:' in tor.stdout"

  roles:
    - role: charlesrocket.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
#   - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/yabai.yml

    - include_tasks: tasks/configuration.yml

    - include_tasks: tasks/app-configs.yml

    - include_tasks: tasks/hardening.yml

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
