---
downloads: ~/.ansible-downloads/

dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/Documents/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .gitignore
  - .zshrc

configure_dotfiles: yes
configure_ui: yes
configure_apps: yes
configure_settings: yes
configure_karabiner: yes

configure_ruby: yes
ruby_version: 3.0.0

install_homebrew_if_missing: true
homebrew_packages:
  - ansible-lint
  - arduino
  - arduino-cli
  - autoconf
  - bash-completion
  - burp-suite
  - clamav
  - clang-format
  - cmake
  - cocoapods
  - coreutils
  - crystal
  - direnv
  - doxygen
  - fastlane
  - gettext
  - git
  - go
  - gzip
  - hashcat
  - help2man
  - heroku
  - httpie
  - imagemagick
  - ipcalc
  - iperf3
  - jq
  - kubernetes-cli
  - libevent
  - links
  - makepkg
  - mc
  - minisign
  - ncdu
  - neofetch
  - ninja
  - nmap
  - node
  - nvm
  - pam_yubico
  - openssl
  - protobuf
  - php
  - python3
  - qemu
  - qmk
  - rbenv
  - rename
  - ruby-build
  - speedtest-cli
  - ssh-copy-id
  - tldr
  - tmux
  - tor
  - unzip
  - wakeonlan
  - weechat
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - heroku/brew
  - qmk/qmk

homebrew_cask_packages:
  - atom
  - balenaetcher
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - gpg-suite-no-mail
  - gqrx
  - hex-fiend
  - imageoptim
  - joplin
  - karabiner-elements
  - lastfm
  - oversight
  - slack
  - unetbootin
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - wireshark

composer_packages: []

gem_packages:
  - name: bundler
    state: present
    version: "~> 1.15.1"

npm_packages: []

pip_packages:
  - name: virtualenv
    state: present
    version: "20.2.2"
    executable: pip3

post_provision_tasks: []
